name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: conventional_commits
          increment: patch

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{ env.IMAGE_NAME }}:${{ steps.version.outputs.prefixed-v-version }}"
          file: GluetunExtendarr.Console/Dockerfile
          context: .

      - name: Create Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.prefixed-v-version }}
          tag_prefix: ""

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.prefixed-v-version }}
          name: Release ${{ steps.version.outputs.prefixed-v-version }}
          generateReleaseNotes: true
          prerelease: true
